SRCS = main.c factorial.c hello.c
OBJS = $(SRCS:.c=.o)
TARGET = hello
CFLAG = -Wall -g 
LFLAGS = -L/home/test/lib -L../lib
INCLUDES = -I../include
LIBS = -lm 
CC = gcc 

all: ${TARGET}

hello: ${OBJS}
	  ${CC} ${CFLAGS} -o ${TARGET} ${OBJS} ${LFLAGS} ${LIBS}


# this is a suffix replacement rule for building .o's from .c's
# it uses automatic variables $<: the name of the prerequisite of
# the rule(a .c file) and $@: the name of the target of the rule (a .o file) 
# (see the gnu make manual section about automatic variables)
.c.o: 
	${CC} ${CFLAGS} $(INCLUDES) -c $< -o $@

clean: 
	   rm -f ${OBJS} ${TARGET}


depend: $(SRCS)
	makedepend $(INCLUDES) $^

